name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - uses: actions/setup-node@v2

    - name: Build Web
      working-directory: web
      run: |
        yarn install
        yarn product

    - name: Artifact Upload
      uses: actions/upload-artifact@v2
      with:
        name: Evil-Reddit Latest
        path: web/js/*.js
