name: Build

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./web

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: yarn install
    - run: yarn product
